<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use App\Models\Color;
use Illuminate\Support\Facades\Session;
use Tests\TestCase;

class BoardTest extends TestCase
{
    use WithFaker, RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();
    }

    /** @test */
    public function a_user_can_create_a_new_board()
    {
        $user = $this->signIn();

        $board_data = [
            'name' => 'fake',
            'user_id' => $user->id,
            'color_id' => Color::first()->id
        ];

        $board = $this->handleRequest('/board', 'post', $board_data, 'board');

        $this->assertEquals($board_data['name'], $board->name);

        // test board id to enable share the board, hint: use uniqid()
        $this->assertEquals(13, strlen($board->share_board_id));

        // make sure relations are built
        $this->assertEquals($user->id, $board->user->id);
        $this->assertEquals($board_data['color_id'], $board->color->id);
    }

}
