<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TaskTest extends TestCase
{
    use WithFaker, RefreshDatabase;

    private $task, $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();

        $this->user = $this->signIn();

        $this->task = [
            'title' => 'foo',
            'description' => 'lorem ipsum ...',
            'priority' => 'high',
            'due_time' => time() + 10000,
            'status' => 'pending'
        ];
    }

    /** @test */
    public function a_user_can_create_new_task()
    {
        $task = $this->handleResponseRequest('/task', 'post', $this->task, 'tasks');

        $this->assertEquals($this->task['title'], $task);
    }

    /** @test */
    public function a_user_can_update_his_task()
    {
        # code...
    }

    /** @test */
    public function a_user_can_delete_his_task()
    {

    }

    /** @test */
    public function a_user_can_mark_his_task_as_completed()
    {
        # code...
    }

    /** @test */
    public function a_user_can_get_back_the_status_of_his_task_to_pending()
    {
        # code...
    }
}
