<?php

namespace Tests\Feature;

use App\Models\Color;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TaskTest extends TestCase
{
    use WithFaker, RefreshDatabase;

    private $task, $board, $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();

        $this->user = $this->signIn();

        $this->board = $this->handleResponseRequest('/board', 'post', [
            'name' => "fake board",
            'user_id' => $this->user->id,
            'color_id' => Color::first()->id
        ], 'board');

        $this->task = [
            'title' => 'foo',
            'description' => 'lorem ipsum ...',
            'priority' => 'high',
            'status' => 'pending',
            'board_id' => $this->board->id
        ];
    }

    /** @test */
    public function a_user_can_create_new_task()
    {
        $task = $this->insertNewTask();

        $this->assertEquals($this->task['title'], $task->title);

        $this->assertEquals($this->board->name, $task->board->name);
    }

    /** @test */
    public function a_user_can_update_his_task()
    {
        $task = $this->insertNewTask();

        $titleUpdated = $this->task['title'] = 'foo update';

        $taskUpdated = $this->updateATask($task->id);

        $this->assertEquals($titleUpdated, $taskUpdated->title);
    }

    /** @test */
    public function a_user_can_delete_his_task()
    {
        $task = $this->insertNewTask();

        $this->deleteATask($task->id)->assertStatus(302);
    }

    /** @test */
    public function a_user_can_mark_his_task_as_completed()
    {
        $task = $this->insertNewTask();

        $request = $this->sendRequest('/task/'.$task->id.'/completed', 'put', [], 'task');

        $request->assertOk();
    }

    /** @test */
    public function a_user_can_get_back_the_status_of_his_task_to_pending()
    {
        $task = $this->insertNewTask();

        $request = $this->sendRequest('/task/'.$task->id.'/completed', 'put', [], 'task');
        $request->assertOk();

        $request = $this->sendRequest('/task/'.$task->id.'/pending', 'put', [], 'task');
        $request->assertOk();
    }

    private function insertNewTask()
    {
        return $this->handleResponseRequest('/task', 'post', $this->task, 'task');
    }

    private function updateATask($id)
    {
        return $this->handleResponseRequest('/task/' . $id, 'put', $this->task, 'task');
    }

    private function deleteATask($id)
    {
        return $this->sendRequest('/task/'.$id, 'delete', []);
    }
}
