<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use App\Models\Color;

class ColorTest extends TestCase
{
    use RefreshDatabase;

    private $color;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();

        $this->color = Color::first();
    }

    /** @test */
    public function the_color_has_a_name()
    {
        $this->assertIsString($this->color->name);
    }

    /** @test */
    public function the_color_in_hex()
    {
        $code = $this->color->code;

        $this->assertStringStartsWith('#', $code);
        $this->assertEquals(7, strlen($code));
    }
}
